version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - redis
        ports:
            - "5000:5000"
    redis:
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"